[project]
name = "handtracking"
version = "0.1.0"
description = "Program for tracking hands to manipulate digital shapes"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.14",
    "opencv-python>=4.12.0.88",
]
